### ISSUE TITLE
learning_start_date e learning_end_date di AttendedLearnings hanno un formato diverso

### ISSUE THREAD

**Issue by s-cenni** [italia/api-padigitale2026-misura1.3.1-uni-afam#245]
Buongiorno,
segnalo che le definizioni dei campi learning_start_date e learning_end_date hanno un formato diverso:
https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS03-titoli.yaml#L954

Nella generazione delle classi Java partendo da questo YAML learning_start_date è una stringa mentre learning_end_date è una data.
Se è possibile potreste utilizzare per learning_start_date la stessa definizione utilizzata per learning_end_date?

```
        learning_start_date:          
          type: string
          description: Course start date / Data inizio corso
          example: 2018-12-01          
          minLength: 10
          maxLength: 10
          nullable: true
        learning_end_date:          
          type: string
          format: date
          description: Course end date / Data fine corso
          example: 2019-03-01          
          nullable: true
```
